### PR TITLE
feat(ctf_ranged/wep_logic): added entity_projectile flag to weapon defs

### PR DESCRIPTION
**Pull request by Beanzilla**
Any weapon can set this flag to enable entity spawning via the flag (e.g. setting the flag to "ctf_ranged:rocket" would spawn a ctf_ranged:rocket entity)

```lua
ctf_ranged.simple_register_gun("ctf_ranged:rpg", {
  type = "pistol",
  description = "RPG",
  texture = "rangedweapons_rocketlauncher.png",
  fire_sound = "ctf_ranged_mp5fire",
  rounds = 1,
  range = 50,
  damage = 30,
  automatic = false,
  fire_interval = 0.6,
  liquid_travel_dist = 2,
  entity_projectile = "ctf_ranged:rocket_entity", -- Will spawn a ctf_ranged:rocket_entity as projectile
  ammo = "ctf_ranged:rocket"
})
```

**Warning: Un-tested code base**

Due tot the fact that I don't know of any good entities to spawn as projectiles I didn't test that any of this works. (So expect what I've submitted to fail)

### CODE REVIEW

**Comment by Beanzilla** [comment]
I like how I renamed the tier1 makarov into a RPG :)

But to show the point I was making, it should become that simple, and as far as what the old code base needs to do it needs NOTHING to change to add this feature (quite simply because if the field is empty or doesn't exist we carry onto ray based projectiles)

**Comment by natelastname** [comment]
I changed my mind about how to go about implementing this feature. Because different entities have to be initialized with different information, it would be better to allow passing of an on_fire callback function to simple_register_gun instead of a an entity name. This is an easy feature to implement, and I've done it already locally. I'm still working on the grenade entity.

**Comment by Beanzilla** [comment]
Ok, Well I guess I will close this PR.

> Probably better, since my code would require considerably more work (just to test it out).

Some interesting ideas for weapons I was thinking of:

- Single-round RPG (Your classic RPG)
- Multi-round Quad-RPG (4 shots per rocket mag)
- Single-round GL Thumper
- Multi-round GL (6 shots per mag)

Of course the idea is to keep the change between the 2 types of weapon systems minimal. (Between ray and entity based systems that is)

**Comment by Beanzilla** [comment]
> Keep chatting here though.

**Comment by natelastname** [comment]
I just pushed some changes to master. I added the grenades mod for explosive projectiles and implemented a grenade launcher weapon (the m79.)

**Pull request closed without merging**
