### PR TITLE
Mcl support

### PR DESCRIPTION
**Pull request by Beanzilla**
Ever wanted to use our guns in a Minecraft like world? (MineClone2, MineClone5, or even MineClonia)

While the recipes changed the mod remains the same. (Same great guns, same great features, just different crafting)

### CODE REVIEW

**Comment by Beanzilla** [comment]
This closes #10

**Comment by natelastname** [comment]
This looks very promising. I'll hopefully get this merged tomorrow. Great work!

**Comment by Beanzilla** [comment]
Yeah the only thing that seems to not work quite right out of the box is zoom. (Currently I hacked it so it at least doesn't give any errors, but it also doesn't do anything either)

> It's at least a step towards getting 2 games supported. (Just need to update the Readme here for the repo and also update content dbs page)

**Comment by natelastname** [comment]
> Yeah the only thing that seems to not work quite right out of the box is zoom. (Currently I hacked it so it at least doesn't give any errors, but it also doesn't do anything either)
> 
> > It's at least a step towards getting 2 games supported. (Just need to update the Readme here for the repo and also update content dbs page)

In that case, give me a few more days. I know how to fix this.

**Comment by Beanzilla** [comment]
I guess we can just make a disclaimer that in MineClone scopes don't work right. (Or maybe look at mcl_spyglass, they have a binoculars zoom feature)

**Comment by Beanzilla** [comment]
> I couldn't get scopes working. I think something weird is going on in Mineclone that makes it ignore the zoom_fov player property.

In mcl_spyglass they directly change the fov not the zoom_fov.

[https://github.com/NO411/mcl_spyglass/blob/main/init.lua#L60-L71](https://github.com/NO411/mcl_spyglass/blob/main/init.lua#L60-L71)

**Comment by Beanzilla** [comment]
I'll make a mcl_scopes branch and get the mcl_spyglass fov trick installed and see how it works.

**Pull request merged**
